# Generated by Django 4.0 on 2022-01-26 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todoapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersapp.baseuser'),
        ),
        migrations.AddField(
            model_name='todo',
            name='related_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
