# Generated by Django 4.0 on 2021-12-29 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eda0af03-e0c1-4d26-aac2-4f9d8d8c8f84'), primary_key=True, serialize=False),
        ),
    ]
