# Generated by Django 4.0 on 2022-01-18 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_baseuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ccd28739-e546-4ba1-99e3-82fd6b91ce62'), primary_key=True, serialize=False),
        ),
    ]
